# SAM File
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: A starter AWS lambda function.
Resources:
  helloworldpython3:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: app.lambda_handler # file_name.function_name
      Runtime: python3.11
      CodeUri: src/
      Description: A starter lambda function.
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME: !Ref myTable # defined below
          REGION_NAME: !Ref AWS::Region # pseudo param
      Events:
        HelloWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello # when we go to /hello with GET method
            Method: GET # we should invoke our lambda handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref myTable
  myTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: greeting
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
